#!/usr/bin/env python3
"""
Single source of truth: config.json's "primary_monitor_name".
Regenerates the Hyprland workspace-assignment rules file from a template,
then reloads Hyprland so it takes effect immediately.

Run this any time you change "primary_monitor_name" in config.json —
or just run it as part of Ax-Shell's own startup, so it's always in sync.
"""
import json
import subprocess
import sys
from pathlib import Path

CONFIG_PATH = Path.home() / ".config" / "Ax-Shell" / "config" / "config.json"
WORKSPACES_CONF_PATH = Path.home() / ".config" / "hypr" / "workspaces.conf"


def get_connected_monitor_names() -> list[str]:
    result = subprocess.run(
        ["hyprctl", "monitors", "-j"], capture_output=True, text=True, check=True
    )
    monitors = json.loads(result.stdout)
    return [m["name"] for m in monitors]


def load_config() -> dict:
    with open(CONFIG_PATH, "r") as f:
        return json.load(f)


def generate_workspace_rules(primary_name: str, all_names: list[str], per_monitor: int) -> str:
    if primary_name not in all_names:
        print(f"[sync_primary_monitor] WARNING: '{primary_name}' not currently connected. "
              f"Connected monitors: {all_names}. Rules will still be written for when it reconnects.")

    ordered = [primary_name] + [n for n in all_names if n != primary_name]
    # Include primary even if not currently connected, so rules are ready when it plugs back in
    if primary_name not in ordered:
        ordered = [primary_name] + ordered

    lines = ["# AUTO-GENERATED by sync_primary_monitor.py — do not edit by hand\n"]
    for block_index, name in enumerate(ordered):
        start = int(block_index) * int(per_monitor) + 1
        for i in range(int(per_monitor)):
            ws = start + i
            default = "true" if i == 0 else "false"
            lines.append(
                f"workspace = {ws}, monitor:{name}, persistent:true, default:{default}"
            )
    return "\n".join(lines) + "\n"


def main():
    config = load_config()
    primary_name = config.get("primary_monitor_name")
    per_monitor = config.get("workspaces_per_monitor", 5)

    if not primary_name:
        print("[sync_primary_monitor] No 'primary_monitor_name' set in config.json, aborting.")
        sys.exit(1)

    all_names = get_connected_monitor_names()
    rules_text = generate_workspace_rules(primary_name, all_names, per_monitor)

    WORKSPACES_CONF_PATH.write_text(rules_text)
    print(f"[sync_primary_monitor] Wrote {WORKSPACES_CONF_PATH}")

    subprocess.run(["hyprctl", "reload"], check=True)
    print("[sync_primary_monitor] Hyprland reloaded.")


if __name__ == "__main__":
    main()